# Generated by Django 5.1.7 on 2025-04-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_product', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeproduct',
            old_name='custom_price',
            new_name='purchase_price',
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
