# Generated by Django 5.1.7 on 2025-04-17 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        ('purchase_order', '0002_initial'),
        ('store', '0003_rename_loaction_store_location'),
        ('supplier', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_store', to='store.store'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_product', to='product.product'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_supplier', to='supplier.supplier'),
        ),
    ]
