# Generated by Django 5.1.7 on 2025-04-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='loaction',
            new_name='location',
        ),
    ]
