# Generated by Django 5.1.7 on 2025-04-19 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointmaster',
            name='title',
            field=models.CharField(default=datetime.datetime(2025, 4, 19, 14, 17, 16, 77443, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
