# Generated by Django 5.2 on 2025-04-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_permission', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='rolepermission',
            table='role_permission',
        ),
    ]
