# Generated by Django 5.1.7 on 2025-04-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_permission', '0002_rolepermission_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolepermission',
            name='model',
        ),
    ]
