# Generated by Django 5.1.7 on 2025-04-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_permission', '0003_remove_rolepermission_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=set(),
        ),
    ]
