# Generated by Django 5.1.7 on 2025-04-17 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
        ('product', '0003_rename_price_product_unit_price'),
        ('sales_order', '0002_initial'),
        ('store', '0003_rename_loaction_store_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_store', to='store.store'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_customer', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_product', to='product.product'),
        ),
    ]
