# Generated by Django 5.1.7 on 2025-04-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0003_salesorder_store_alter_salesorder_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
